### ISSUE TITLE
Support for choosing multiple files

### ISSUE THREAD

**Issue by shalva97** [Wavesonics/compose-multiplatform-file-picker#10]
Just as the title says and a TODO here https://github.com/Wavesonics/compose-multiplatform-file-picker/blob/32cb12892f0a8c3602c9bce9ee64094156d2c4a2/mpfilepicker/src/jsMain/kotlin/com/darkrockstudios/libraries/mpfilepicker/JsFilePicker.kt#L33

**Comment by DATL4G** [comment]
@shalva97 Any progress on this?

**Comment by shalva97** [comment]
nope, my priorities are a bit different currently. But I will be happy for a PR.

**Comment by Shahriyar13** [comment]
https://github.com/Wavesonics/compose-multiplatform-file-picker/pull/86
