### ISSUE TITLE
Android photo chooser

### ISSUE THREAD

**Issue by mahramane** [Wavesonics/compose-multiplatform-file-picker#105]
Hi
Please add an option that when i want to only choose photo in android
open file chooser like following image:
![telegram-cloud-photo-size-4-5825822451114819424-y](https://github.com/Wavesonics/compose-multiplatform-file-picker/assets/38125729/09fef444-4a2d-41ea-8fb9-fa086fa42933)

**Comment by StefanOltmann** [comment]
https://github.com/TEAM-PREAT/peekaboo already does that.

**Comment by mahramane** [comment]
> https://github.com/TEAM-PREAT/peekaboo already does that.

But it's just for android and ios :(
Please also work on jvm and wasmJs.

**Comment by StefanOltmann** [comment]
> > https://github.com/TEAM-PREAT/peekaboo already does that.
> 
> But it's just for android and ios :( Please also work on jvm and wasmJs.

And from which library should it choose?

**Comment by mahramane** [comment]
> > > https://github.com/TEAM-PREAT/peekaboo already does that.
> > 
> > 
> > But it's just for android and ios :( Please also work on jvm and wasmJs.
> 
> And from which library should it choose?

For Jvm and Wasmjs you can use File picker with image formats filter to choose photo.

**Comment by StefanOltmann** [comment]
> > > > https://github.com/TEAM-PREAT/peekaboo already does that.
> > > 
> > > 
> > > But it's just for android and ios :( Please also work on jvm and wasmJs.
> > 
> > 
> > And from which library should it choose?
> 
> For Jvm and Wasmjs you can use File picker with image formats filter to choose photo.

This is already possible on Windows, macOS and Linux.

WasmJS file picker is missing, but I opened #101 for that.
