### ISSUE TITLE
"sun/misc/Unsafe" occurs when running in native

### ISSUE THREAD

**Issue by DeeChael** [Wavesonics/compose-multiplatform-file-picker#106]
![image](https://github.com/Wavesonics/compose-multiplatform-file-picker/assets/63186003/bae2c4c9-8d58-411b-8697-4f7692abb20d)

I compiled my application to distribution and running the exe, when I clicked the button to open the file picker, a dialog appears showing the content above

**Comment by tangshimin** [comment]
related issue https://github.com/Wavesonics/compose-multiplatform-file-picker/issues/87
