### ISSUE TITLE
Add iOS support

### ISSUE THREAD

**Issue by Wavesonics** [Wavesonics/compose-multiplatform-file-picker#14]
would be great to get this platform implemented

**Comment by shalva97** [comment]
I think we can start this by exploring this Dart library https://pub.dev/packages/flutter_file_dialog it supports both IOS and Android

**Comment by aguragorn** [comment]
maybe this can help, https://github.com/MohamedRejeb/Calf/blob/main/calf-file-picker/src/iosMain/kotlin/com.mohamedrejeb.calf.picker/FilePickerLauncher.ios.kt
