### ISSUE TITLE
Support multiple file extensions

### ISSUE THREAD

**Issue by sschuberth** [Wavesonics/compose-multiplatform-file-picker#2]
At least on Windows it's possible to filter for multiple file extensions. Would be nice if `fileExtension` was a list instead of a string to reflect that 😁

**Comment by Wavesonics** [comment]
I agree, will get it in the next version.

**Comment by Wavesonics** [comment]
Closed with this commit: https://github.com/Wavesonics/compose-multiplatform-file-picker/commit/933640747d9b99b8a146e0320039308efa9fa402

Will be included in the next release.

**Comment by stijndcl** [comment]
> Closed with this commit: https://github.com/Wavesonics/compose-multiplatform-file-picker/commit/933640747d9b99b8a146e0320039308efa9fa402
> 
> Will be included in the next release.

@Wavesonics do you plan on creating the next release in the near future? This would be a nice feature to have.

**Comment by Wavesonics** [comment]
yeah I can do it tonight
