### ISSUE TITLE
Use spaces instead of tabs

### ISSUE THREAD

**Issue by shalva97** [Wavesonics/compose-multiplatform-file-picker#25]
According to [default style guide of Kotlin](https://kotlinlang.org/docs/coding-conventions.html#indentation), it should be written with spaces.

For example, tabs are a bit inconsistent, if I copy a line with tabs and paste it somewhere else, it looks like this
```
						println("A call to chooseDirectorySwing failed ${swingException.message}")
```
and in spaces its like this

```
                        println("A call to chooseDirectorySwing failed ${swingException.message}")
```

and in Intellij it looks like this (with a bit of custom settings)

![Screenshot 2023-06-23 at 18 48 10](https://github.com/Wavesonics/compose-multiplatform-file-picker/assets/22417494/0b028e66-45b9-44ce-9c29-1cb935a2792c)

And in Vim or Emacs it will also be different.

So, lets follow default style guide and switch to spaces

**Comment by Wavesonics** [comment]
Tab master race
