### ISSUE TITLE
Heap Corruption crash after using File Picker

### ISSUE THREAD

**Issue by TheSilkMiner** [Wavesonics/compose-multiplatform-file-picker#30]
Showing the `FilePicker` component seems to cause heap corruption and cause the entire Compose application to crash at random times with error code `0xC0000374` (`ERROR_HEAP_CORRUPTION`) on a Windows machine. Given that it seems that Windows itself is killing the process, no JVM error log nor any mini dumps are produced, and the code that is being executed when the application is terminated seems to be random, unrelated to the file picker library itself. Nevertheless, preventing the file picker from showing up consistently solves the issue.

I have managed to replicate the issue somewhat consistently by trying to load Bitmap images through AWT immediately after the file picker is closed: a minimal reproducible test-case is attached below. It does seem that the size of the image does not matter, although the bigger the image is the more likely an error occurs immediately. I have been testing with [this Bitmap](https://blamejared.com/silk/bridge.bmp) and it seems to trigger the error immediately around 90% of the time.

```kotlin
private class C {
    var p by mutableStateOf(false)
    var i by mutableStateOf(false)
}

fun main() {
    application {
        val state = remember { C() }
        Window(onCloseRequest = ::exitApplication) {
            if (state.i) { Image(ImageIO.read(Path("./bridge.bmp").inputStream()).toComposeImageBitmap(), null) }
            Button(onClick = {
                state.p = true
                state.i = false
            }) { Text("Click Me") }
        }
        FilePicker(show = state.p) {
            state.p = false
            state.i = true
        }
    }
}
```

The described behavior can be triggered by clicking on the button and then either choosing a file or canceling the file picking action. Setting `state.i` to `true` by default shows that the image is usually loaded without problems if the file picker is not involved.

These tests have been performed with version 1.2.0 of this library along with Compose 1.2.0 with Kotlin 1.8.21 (requires manually specifying version 1.4.7 of the Compose compiler in the project settings) on Java 17.

**Comment by TheSilkMiner** [comment]
For my use case, the image cannot be read only once as it depends on the choice made by the user in the file picker dialog. As for closing the stream, you are absolutely right that streams should be closed, but I left that out for brevity as it does not seem to have any effect on the crash.

The following code is more similar to my use case, and it triggers the crash if you select the image I linked as the one that should be displayed. Note that in my application, I am storing the actual image as part of the state to avoid having to read the file multiple times if something else happens to change the state, such as a slider being moved, but that also has no impact on whether the application crashes or not.
```kotlin
private class C {
    var p by mutableStateOf(false)
    var i by mutableStateOf(null as String?)
}

fun main() {
    application {
        val state = remember { C() }
        Window(onCloseRequest = ::exitApplication) {
            if (state.i != null) { Image(Path(state.i!!).inputStream().buffered().use { ImageIO.read(it) }.toComposeImageBitmap(), null) }
            Button(onClick = {
                state.p = true
                state.i = null
            }) { Text("Click Me") }
        }
        FilePicker(show = state.p) {
            state.p = false
            state.i = it?.path
        }
    }
}
```

As for the stack trace, it is normal to get none and that is what made figuring out the part of the code responsible really difficult. The error code can be discovered with any tool that allows to inspect the exit code of a process, such as Powershell or IntelliJ Idea itself. In case of Powershell, you can inspect the `$LastExitCode` variable after the process has terminated, whereas Idea tells you immediately after the program closes in the console window.

**Comment by shalva97** [comment]
man, this sucks, it really is caused by `FilePicker`, which of course is just a wrapper over `Tiny File Dialogs`. How can it be that there is really no fully working library on JVM to pick a file. I really dont get this...

There are actually 2 types of crashes, one is ERROR_HEAP_CORRUPTION and another is with a lot longer logs:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000105726ee8, pid=49068, tid=69123
#
# JRE version: OpenJDK Runtime Environment Corretto-17.0.7.7.1 (17.0.7+7) (build 17.0.7+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (17.0.7+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-amd64)
# Problematic frame:
# V  [libjvm.dylib+0xa57ee8]  bool ConcurrentHashTable<SymbolTableConfig, (MEMFLAGS)10>::get<SymbolTableLookup, SymbolTableGet>(Thread*, SymbolTableLookup&, SymbolTableGet&, bool*)+0xc8
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/shalva/IdeaProjects/compose-multiplatform-file-picker/hs_err_pid49068.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-17/issues/
#
```

also was able to reproduce this on our example in `examples/jvm`. it takes 16-20 triggers of file dialog and then it crashes. I dont know how `inputStream()` makes it crash sooner but yeah, it really is caused by TinyFileDialogs. I dont know what library to add, maybe, there is really no fully working file picker for Java...

A bit later I will add issue on https://github.com/LWJGL/lwjgl3, maybe they will fix it

**Comment by shalva97** [comment]
Somehow was able to figure this out, it was not caused by tinyFileDialogs. The PR is ready. @Wavesonics can you take a loot later?
