### ISSUE TITLE
Publish failure

### ISSUE THREAD

**Issue by Wavesonics** [Wavesonics/compose-multiplatform-file-picker#32]
Looks like our publish task is failing now with the JS target:
```
 A problem was found with the configuration of task ':mpfilepicker:publishAndroidReleasePublicationToMavenRepository' (type 'PublishToMavenRepository').
  - Gradle detected a problem with the following location: '/home/runner/work/compose-multiplatform-file-picker/compose-multiplatform-file-picker/mpfilepicker/build/libs/mpfilepicker-2.0.0-javadoc.jar.asc'.
    
    Reason: Task ':mpfilepicker:publishAndroidReleasePublicationToMavenRepository' uses this output of task ':mpfilepicker:signJsPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':mpfilepicker:signJsPublication' as an input of ':mpfilepicker:publishAndroidReleasePublicationToMavenRepository'.
      2. Declare an explicit dependency on ':mpfilepicker:signJsPublication' from ':mpfilepicker:publishAndroidReleasePublicationToMavenRepository' using Task#dependsOn.
      3. Declare an explicit dependency on ':mpfilepicker:signJsPublication' from ':mpfilepicker:publishAndroidReleasePublicationToMavenRepository' using Task#mustRunAfter.
    
```
https://github.com/Wavesonics/compose-multiplatform-file-picker/actions/runs/5432985513/jobs/9880387821

**Comment by Wavesonics** [comment]
@shalva97 hhmmm we may want to rollback the JS & Mac targets until we can solve the publish issues. It'd be good to get the JVM fix out.

**Comment by shalva97** [comment]
is rolling back only option? maybe somehow its possible to skip publishing of those 2 targets and keep the code. 

Also my guess is that android should not know about JS target, because it is a different source set...

**Comment by shalva97** [comment]
I think it is this line https://github.com/Wavesonics/compose-multiplatform-file-picker/blob/a8e98ecbf1961e9f2bf18ee04a256133b2237c06/mpfilepicker/build.gradle.kts#L167. not 100% sure but it looks like this line gived android a dependency on JS task

**Comment by Wavesonics** [comment]
Oh I meant leave the code, just comment them out from gradle for this release.

But you were right, that line was part of me trying to fix the Js publish target, and it was getting applied too broadly.

**Comment by shalva97** [comment]
I also hate Github Actions :D

**Comment by shalva97** [comment]
Is 2.0.0 released? https://github.com/Wavesonics/compose-multiplatform-file-picker/issues/35 and https://github.com/Wavesonics/compose-multiplatform-file-picker/issues/30 issues should be fixed

**Comment by shalva97** [comment]
One more thing. before you publish a new release press `generate release notes`, this will create a much better list of what changed.

![Screenshot 2023-07-06 at 18 20 25](https://github.com/Wavesonics/compose-multiplatform-file-picker/assets/22417494/270e4b64-9732-4421-b7f7-a7112ae2c1a6)
![Screenshot 2023-07-06 at 18 20 40](https://github.com/Wavesonics/compose-multiplatform-file-picker/assets/22417494/c6bdd8d1-6517-4539-b5de-a1b45f26e384)

**Comment by shalva97** [comment]
Will close this because 2.0.2 is released
