### ISSUE TITLE
file extension, if not explicitly specified, should allow any file to be selected.

### ISSUE THREAD

**Issue by tangshimin** [Wavesonics/compose-multiplatform-file-picker#35]
platforms：windows

Describe the bug
Prior to 1.2.0,  if no file extension is set, any file can be selected.
After 1.2.0, if no file extension is set, no file can be selected.

**Comment by shalva97** [comment]
As I remember I fixed this at line https://github.com/Wavesonics/compose-multiplatform-file-picker/blob/6830ff5a8ac611017b6f420aef6f9fb07bb46a59/mpfilepicker/src/jvmMain/kotlin/com/darkrockstudios/libraries/mpfilepicker/FileChooser.kt#L60

@Wavesonics it is released, right?

**Comment by tangshimin** [comment]
is 2.0 fixed? 
2.0 publish failed, Maven Central Repository latest version still is 1.2.0  https://central.sonatype.com/artifact/com.darkrockstudios/mpfilepicker-desktop/1.2.0/versions

**Comment by shalva97** [comment]
@tangshimin can you check it with 2.0.2 version? it is released

**Comment by tangshimin** [comment]
> @tangshimin can you check it with 2.0.2 version? it is released

I tested v2.0.2 and it did fix the bug. thank you!

**Comment by Yash-Garg** [comment]
This doesn't seem to work properly on Android for me.

If I don't specify and file types it just shows this and no hamburger menu is present:

![image](https://github.com/Wavesonics/compose-multiplatform-file-picker/assets/33605526/cb535237-718c-4596-8069-b155fc72a6e4)

**Comment by Yash-Garg** [comment]
This doesn't seem to work properly on Android for me (latest version).

```kotlin
FilePicker(showFilePicker) { file ->
    showFilePicker = false
    Napier.e("File: $file")
}
```

If I don't specify any file types it just shows this and no hamburger menu is present:

<img src="https://github.com/Wavesonics/compose-multiplatform-file-picker/assets/33605526/cb535237-718c-4596-8069-b155fc72a6e4" width="70%" />
