### ISSUE TITLE
Lower android minSdk to 21

### ISSUE THREAD

**Issue by zt64** [Wavesonics/compose-multiplatform-file-picker#42]
Hi, just found this lib and it'll be of great use for my multiplatform app i'm developing. One problem I've found is that the library has its minSdk set to 24, and my app is minSdk 21. I inspected the code and there doesn't appear to be anything preventing it from being dropped down. Perhaps I overlooked something but otherwise I'm certain the minSdk can be lowered to 21. Compose min sdk is also 21.

**Comment by shalva97** [comment]
Can you try with 2.1.0 version? it should work with SDK 21. If it does not work feel free to reopen this issue
