### ISSUE TITLE
Why platformFile of MPFile is generic?

### ISSUE THREAD

**Issue by stylerope** [Wavesonics/compose-multiplatform-file-picker#69]
When I debug my project in Windows, if found that the type of plaformFile is always the File of java.io. So I wonder if it is necessary to make it generic? Is it possible to have another type of file?

Thankyou

**Comment by shalva97** [comment]
Yes. If it is java.io, then you are using JVM. In native MacOS this will be NSURL, in JS it is a JS object. In future when we add more platforms, it will be many different objects.
