### ISSUE TITLE
Version 3.0.0 was not published to maven

### ISSUE THREAD

**Issue by alaegin** [Wavesonics/compose-multiplatform-file-picker#80]
Hello!

I'm trying to use this library for iOS and Android KMP app, but it seems like the new version was not published to Maven.
Maven central says that the latest version is 2.1.0
https://central.sonatype.com/search?q=com.darkrockstudios

It would be nice to have the new version published :)

**Comment by VitalyPeryatin** [comment]
I am waiting too

**Comment by StefanOltmann** [comment]
@Wavesonics Can you please publish the artifacts on Maven Central?

**Comment by Wavesonics** [comment]
There seems to be a problem with the github action that publishes to maven, so there's nothing there to publish yet. Will need to debug the build & publish action.

**Comment by StefanOltmann** [comment]
@Wavesonics: That's unusual. I encountered a similar issue in the past. In my situation, I retried the process, and it ended up working. It might be worth running it again with version 3.0.1 to check if it was just a temporary problem.

**Comment by shalva97** [comment]
I have triggered same workflow twice and it was successful: https://github.com/Wavesonics/compose-multiplatform-file-picker/actions/runs/6683377891/job/18402057926#step:5:191

I don't know what could be the isssue here, 3 PRs where merged but they should not have an effect on publishing.

**Comment by shalva97** [comment]
I think it got released. Just got this on my project https://github.com/shalva97/Youtube_history_parser/pull/126

**Comment by StefanOltmann** [comment]
@shalva97 Thank you. Yes, it's available and it works on iOS. :) Great job!

@alaegin Issue can be closed.

**Comment by StefanOltmann** [comment]
I encountered a hiccup while attempting to release a new version of https://github.com/Ashampoo/xmpcore to Maven Central. The initial upload was rejected due to invalid signatures, but a subsequent workflow run successfully produced valid signatures.

There appears to be an issue at the moment, which could be related to Maven Central or a potential bug in the publishing plugin.
