### ISSUE TITLE
Why do you call JVM variant "desktop"

### ISSUE THREAD

**Issue by shalva97** [Wavesonics/compose-multiplatform-file-picker#9]
It is confusing. There is line in gradle file `jvm("desktop")` and the sourceSet is called `desktopMain`. I think if it had its original name then it would be more intuitive

**Comment by Wavesonics** [comment]
`multiplatform compose` was originally called `desktop compose`, so thats where it came from. That being said, that target is specifically meant to target the 3 desktop platforms: MacOS, Linux, Windows

Other source sets target Android & web. What other platform would the JVM source set target that isn't one of the desktop OSs?

**Comment by shalva97** [comment]
The thing is that Kotlin can also compile to native, meaning there will be no jVM needed. Compose can run without JVM so thats why,, jvm("desktop") is unintuitive, one has to read gradle file to understand that its jvm variant.

nit: change `jvm("desktop")` to just `jvm()`
